/* groovylint-disable CompileStatic, NestedBlockDepth */
pipeline {
  agent any

  stages {
    stage('Checkout Source') {
      steps {
        git url:'https://github.com/guysade/Stocks.git', branch:'master'
      }
    }
      stage('Build image') {
            steps {
                script {
                    myapp = docker.build("guysade4/stocks:${env.BUILD_ID}")
                }
            }
        }
      stage('Push image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                            myapp.push('latest')
                            myapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
    stage('Deploy App') {
      steps {
        script {
          kubernetesDeploy(configs: 'hellowhale.yml', kubeconfigId: 'mykubeconfig')
        }
      }
    }
  }
}